### ISSUE TITLE
Routing?

### ISSUE THREAD

**Issue by L3P3** [L3P3/lui#20]
I don't know if it makes sense, but maybe I should integrate some sort of routing, eg.:

```js
function PageStart() {
	return [
		node_dom('h1[innerText=Hallo, Welt!]'),
		node_dom('p', null, [
			node_dom('a[href=#/blah][innerText=Blah]')
		])
	];
}

function PageBlah() {
	const [sdl, sdl_set] = hook_route();
	return [
		node_dom('h1', {
			innerText:
				sdl !== ''
				?	`Seite ${sdl}`
				:	'Sinnlose Seite'
		}),
		node_dom('p', null, [
			node_dom('input[type=number]', {
				value: sdl,
				onchange: event => {
					const value = parseInt(event.target.value);
					!isNaN(value) &&
						sdl_set(value)
				}
			})
		])
	];
}

init(() => {
	return[
		null,
		[
			node_route({
				blah: PageBlah
			}, PageStart)
		]
	];
});
```

With this approach, there would be a `hook_route` that behaves like `hook_state` but is bound to the matching url part. A `node_route(Object<string, Component>, Component, props=)` could be used to handle pagination, including a default route.

**Comment by L3P3** [comment]
# Pro
- Required for TodoMVC
- _Could_ be very useful
# Contra
- Would increase file size by about 0.3k

**Comment by johann-lr** [comment]
A router is a basic requirement for larger web applications, it shouldn't fail because of a size of ~0.3k

**Comment by L3P3** [comment]
Have not considered that, thanks for your valuable input!

**Comment by L3P3** [comment]
Will not be implemented into lui but maybe into an extended version of lui later.

**Comment by johann-lr** [comment]
What about creating more lui modules (like routing) that can be required optionally? Most of the web frameworks follow this approach to keep the coverage of the main framework as high as possible and the code more minimalistic.

**Comment by L3P3** [comment]
I plan to do this. I develop so many universally useful features for prog that I want to auslagern in a dedicated library like lui-ext.
