### ISSUE TITLE
Types(cript)

### ISSUE THREAD

**Issue by johann-lr** [L3P3/lui#21]
## Why?

* Imagine you're eating a hot dog and there are no roasted onions on it... or you've prepared breakfast but there's only fruit tea - that's exactly why we need typing to build an app using perfectly typed typescript.
* JS can become more messy than the house of the Ritter family

## How?

idk

**Comment by L3P3** [comment]
Yes, I totally agree that I/we need typescript headers!
I have no idea how to do that thou, I would have to learn about TS first.
But you are invited to create the headers and do a pull request. :wink:
