### ISSUE TITLE
Rename node_list?

### ISSUE THREAD

**Issue by L3P3** [L3P3/lui#23]
As pointed out by JL, `node_list` may be misleading since we already return "lists" (=arrays) from components.
Here are some alternatives:
- `node_list`
  - Current name, easy meaning as it takes a list and creates a list of components
  - Not very precise
- `node_map`
  - Same terminology as in other frameworks (`[].map(itm => <Component />)`)
  - Could be confused with graphical maps
- `node_dynamic`
  - It highlights the fact that its childs can be changed dynamically unlike it is the case otherwise
  - A bit long and other things could also be dynamic

I consider renaming it to `node_map`... Are there any opinions on that?

**Comment by johann-lr** [comment]
'clearly vote for `node_dynamic` since it describes the functionality as good as possible in my eyes.

**Comment by L3P3** [comment]
I would vote for `node_map` but if you are that certain, I go your way!

**Comment by bjoern-quast** [comment]
`node_dynamic` is a singular, that is not precise.

**Comment by L3P3** [comment]
Or maybe just `nodes`? 😃

**Comment by L3P3** [comment]
Or `node_for`? `nodes_for` would mess up the naming scheme as all node types begin with `node`...

**Comment by bjoern-quast** [comment]
So I suggest `nodes_dynamic`, if it otherwise clear that it's a mapping.

**Comment by L3P3** [comment]
Problem with plural is that it still returns just one node like the other node* methods. The returned node has child nodes thou...
It is really hard to decide I think.

**Comment by L3P3** [comment]
I think I will go with `node_dynamic` if no other new idea or point comes in here.

**Comment by bjoern-quast** [comment]
`list` and `map` both indicate the nature of the node as containing multiple other nodes of the same kind, clearly that's not the case for any `node`? Or is the defining feature actually that the containing nodes can be changed and you could just create a similar node (not dynamic), where that isn't the case?

**Comment by L3P3** [comment]
We have `node` which mounts a component, `node_html` which adds a html element and `node_list` which mounts a component n times for each item of an array.
All of these return just one node representing its meaning.

**Comment by L3P3** [comment]
I prefer `node_map`. `node_dynamic` is too unprecise I think.

**Comment by L3P3** [comment]
Sorry, @johann-lr I will go for `node_map`. :wink:
