### ISSUE TITLE
Class-based components

### ISSUE THREAD

**Issue by johann-lr** [L3P3/lui#28]
Components written in functions are made for virgin react developers. I get the idea behind the hooks but... no.

**Why?**

* Structure (f.ex. regarding the state or the component's lifecycle)
* Readability (yep, this is a rather personal thing, but there would be no need to pass a lot of "null" parameters everywhere :))

https://open.spotify.com/track/11RdQ7zGzEfRuXcZW5sb1Y?si=9C6QB5pVQYaSFzEK-wuyWA

**Comment by L3P3** [comment]
You are invited to use mithril or preact instead. :facepalm:

**Comment by johann-lr** [comment]
ok bye 👋🏻

**Comment by L3P3** [comment]
Maaaaaaaaaaaaaan du ruinierst hiermit meine ganze, wertvolle Reputation! Was fällt dir ein?
Na warte...

**Comment by johann-lr** [comment]
Ich könnte hier eigentlich auch einen "pointless"-Kommentar mit einem React Link ergänzen. höhö

**Comment by L3P3** [comment]
Nö, die Vorteile von lui gegenüber React liegen auf der Hand... auf meiner zumindest. Hast du die Readme gelesen?

**Comment by L3P3** [comment]
:angry:
