### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Parakoopa** [L3P3/lui#31]
Please add a license to lui, so others can use it:
https://choosealicense.com/

**Comment by Parakoopa** [comment]
The package.json says ISC, if that's the case you should add the ISC to a file called LICENSE.

**Comment by L3P3** [comment]
Isn't the package.json entry enough?
I have no idea about the actual law but I will look into this soon!

**Comment by Parakoopa** [comment]
No, basically you put the license text in a file called LICENSE in the repository usually (you can look around in some other repos for examples)
